# Generated by Django 6.0.1 on 2026-02-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='category',
            field=models.CharField(choices=[('Medical', 'Medical (Blood, Hospital, Emergency)'), ('Education', 'Education (Books, Tuition, Fees)'), ('Job', 'Job & Career Support'), ('Financial', 'Financial Help'), ('Food', 'Food & Daily Needs'), ('Housing', 'Housing / Shelter'), ('Transport', 'Transport Help'), ('Other', 'Other')], max_length=100),
        ),
    ]
