# Generated by Django 6.0.1 on 2026-02-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0002_alter_helprequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open (Waiting for Help)'), ('In Progress', 'In Progress (Someone Helping)'), ('Resolved', 'Resolved (Problem Solved)'), ('Closed', 'Closed (No Longer Active)'), ('Urgent', 'Urgent (Immediate Help Needed)')], default='Open', max_length=50),
        ),
    ]
